// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0oBLAhA398OofECsBFycP_EfchQYQkgQ',
    appId: '1:947815682537:android:23d021479dfbc06d6abb78',
    messagingSenderId: '947815682537',
    projectId: 'gasdash-54378',
    storageBucket: 'gasdash-54378.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2fij6ANJEXOrT9IGzMEO997t5rIY-Eo0',
    appId: '1:947815682537:ios:e956b6397f00ba186abb78',
    messagingSenderId: '947815682537',
    projectId: 'gasdash-54378',
    storageBucket: 'gasdash-54378.firebasestorage.app',
    iosBundleId: 'com.dominiquemorris.gasDash',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFGWd3EjhfFXbaVBN9PqD2xSREKcJuTSQ',
    appId: '1:947815682537:web:acbcbb865c4d0f496abb78',
    messagingSenderId: '947815682537',
    projectId: 'gasdash-54378',
    authDomain: 'gasdash-54378.firebaseapp.com',
    storageBucket: 'gasdash-54378.firebasestorage.app',
    measurementId: 'G-YKQ8X4CE9B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2fij6ANJEXOrT9IGzMEO997t5rIY-Eo0',
    appId: '1:947815682537:ios:e956b6397f00ba186abb78',
    messagingSenderId: '947815682537',
    projectId: 'gasdash-54378',
    storageBucket: 'gasdash-54378.firebasestorage.app',
    iosBundleId: 'com.dominiquemorris.gasDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFGWd3EjhfFXbaVBN9PqD2xSREKcJuTSQ',
    appId: '1:947815682537:web:5b38c8a7409bf2a96abb78',
    messagingSenderId: '947815682537',
    projectId: 'gasdash-54378',
    authDomain: 'gasdash-54378.firebaseapp.com',
    storageBucket: 'gasdash-54378.firebasestorage.app',
    measurementId: 'G-8H14SRNJB3',
  );

}